export const ACTIONS = {

    SELECT:"SELECT",
    RECTANGLE:"RECTANGLE",
    CIRCLE:"CIRCLE",
    SCRIBBLE:"SCRIBBLE",
    ARROW:"ARROW",
    DOWNLOAD:"DOWNLOAD",
    COLOR:"COLOR",
    ERASER:"eraser",
    TEXT:"TEXT"
}